spring:
  application: 
    name: centreon-host-feign-client

server:
  port: 0

feign:
  hystrix: 
    enabled: true
  httpclient:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      
management:
  endpoints:
    web:
      exposure:
        include: "*"