spring:
  application: 
    name: feign-client

server:
  port: 8080

feign:
  hystrix: 
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      
management:
  endpoints:
    web:
      exposure:
        include: "*"