spring:
  application:
    name: gateway

server:
  port: 8080
  
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
 
zuul:
  routes:
    echo:
      path: /document-service/**
      serviceId: my-document-service
      stripPrefix: true
    discovery:
      path: /discovery/**
      url: http://localhost:8761
 
hystrix:
  command:
    my-document-service:
      execution:
        isolation:
          thread: 
            timeoutInMilliseconds: 600000
    discovery:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000
            
my-document-service:
  ribbon:
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    ListOfServers: http://192.168.4.14:35512
    ConnectTimeout: 1000
    ReadTimeout: 3000
    MaxTotalHttpConnections: 500
    MaxConnectionsPerHost: 100