spring:
  application:
    name: gateway

server:
  port: 8080
  
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
 
zuul:
  ignoredServices: "*"
  routes:
    feign:
      path: /document-api/**
      serviceId: feign-client
    centreon-host-feign:
      path: /centreon-api/**
      serviceId: centreon-host-feign-client
    turbine:
      path: /turbine-api/**
      serviceId: turbine-dashboard
    discovery:
      path: /discovery/**
      url: http://localhost:8761  
 
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000

#ribbon:
#  ReadTimeout: 30000
#  SocketTimeout: 30000

management:
  endpoints:
    web:
      exposure:
        include: "*"