spring:
  application:
    name: gateway

server:
  port: 8080
  
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
 
zuul:
  routes:
    document:
      path: /document-service/**
      serviceId: document-service
    discovery:
      path: /discovery/**
      serviceId: discovery
      url: http://localhost:8761
 
hystrix:
  command:
    document-service:
      execution:
        isolation:
          thread: 
            timeoutInMilliseconds: 600000
    discovery:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000