spring:
  application:
    name: gateway

server:
  port: 8080
  
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
 
zuul:
  routes:
    feign:
      path: /document-api/**
      serviceId: feign-client
    turbine:
      path: /turbine-api/**
      serviceId: turbine-dashboard
    discovery:
      path: /discovery/**
      url: http://localhost:8761
 
hystrix:
  command:
    feign:
      execution:
        isolation:
          thread: 
            timeoutInMilliseconds: 600000
    turbine:
      execution:
        isolation:
          thread: 
            timeoutInMilliseconds: 600000
    discovery:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000